name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup checkout
        uses: actions/checkout@v2
      - name: Setup NodeJS v12
        uses: actions/setup-node@v1
        with:
          node-version: 12.22.0
      - name: Install all dependencies
        run: yarn install
      - name: Check for errors
        run: yarn build
      # - name: ESlint check
      #   run: yarn lint
